language: go
os:
  - linux
  #  - osx
go:
  - 1.11.x
go_import_path: github.com/1-bi/fire-di
install:
  - go get ./...
script:
  - go test -v -cover ./...
after_script:
  # examples
  - cd ./_examples
  - go get ./...
  - go test -v -cover ./...
  - cd ../
  # benchmarks
  - cd ./_benchmarks
  - go get ./...
  - go test -run=XXX -bench=. -benchtime=5s
  - cd ../